# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: skill.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bskill.proto\x12\x10grpc.weladee.com\"\xc6\x02\n\tSkillType\x12\x0e\n\x02ID\x18\x01 \x01(\x03R\x02id\x12\x12\n\x04\x43ode\x18\x02 \x01(\tR\x04\x63ode\x12!\n\x0bNameEnglish\x18\x03 \x01(\tR\x0cname_english\x12\x1b\n\x08NameThai\x18\x04 \x01(\tR\tname_thai\x12\x16\n\x06\x41\x63tive\x18\n \x01(\x08R\x06\x61\x63tive\x12/\n\x12\x44\x65scriptionEnglish\x18\x14 \x01(\tR\x13\x64\x65scription_english\x12)\n\x0f\x44\x65scriptionThai\x18\x15 \x01(\tR\x10\x64\x65scription_thai\x12\x12\n\x04Icon\x18\x1e \x01(\tR\x04icon\x12\x12\n\x04Note\x18  \x01(\tR\x04note\x12\x39\n\x0bSkillLevels\x18\x32 \x03(\x0b\x32\x1c.grpc.weladee.com.SkillLevelR\x06levels\"\xa4\x01\n\nSkillLevel\x12\x0e\n\x02ID\x18\x01 \x01(\x03R\x02id\x12\x12\n\x04\x43ode\x18\x02 \x01(\tR\x04\x63ode\x12!\n\x0bNameEnglish\x18\x03 \x01(\tR\x0cname_english\x12\x1b\n\x08NameThai\x18\x04 \x01(\tR\tname_thai\x12\x16\n\x06TypeID\x18\x08 \x01(\x03R\x06typeid\x12\x1a\n\x08Progress\x18\n \x01(\x05R\x08progress\"\xa0\x01\n\x05Skill\x12\x0e\n\x02ID\x18\x01 \x01(\x03R\x02id\x12\x12\n\x04\x43ode\x18\x02 \x01(\tR\x04\x63ode\x12!\n\x0bNameEnglish\x18\x03 \x01(\tR\x0cname_english\x12\x1b\n\x08NameThai\x18\x04 \x01(\tR\tname_thai\x12\x16\n\x06TypeID\x18\x0c \x01(\x03R\x06typeid\x12\x1b\n\x08TypeName\x18\x14 \x01(\tR\ttype_name\"\xcf\x01\n\rEmployeeSkill\x12\x0e\n\x02ID\x18\x01 \x01(\x03R\x02id\x12\x1d\n\tSkillName\x18\n \x01(\tR\nskill_name\x12\x1d\n\tSkillCode\x18\x0c \x01(\tR\nskill_code\x12\x1b\n\x08TypeName\x18\x14 \x01(\tR\ttype_name\x12\x1d\n\tLevelName\x18\x1e \x01(\tR\nlevel_name\x12\x18\n\x07LevelID\x18  \x01(\tR\x07levelid\x12\x1a\n\x08Progress\x18\x64 \x01(\x05R\x08progressB.\n\x1b\x63om.frontware.weladee_skillB\x0bWeladeeGRPCH\x03P\x01\x62\x06proto3')



_SKILLTYPE = DESCRIPTOR.message_types_by_name['SkillType']
_SKILLLEVEL = DESCRIPTOR.message_types_by_name['SkillLevel']
_SKILL = DESCRIPTOR.message_types_by_name['Skill']
_EMPLOYEESKILL = DESCRIPTOR.message_types_by_name['EmployeeSkill']
SkillType = _reflection.GeneratedProtocolMessageType('SkillType', (_message.Message,), {
  'DESCRIPTOR' : _SKILLTYPE,
  '__module__' : 'skill_pb2'
  # @@protoc_insertion_point(class_scope:grpc.weladee.com.SkillType)
  })
_sym_db.RegisterMessage(SkillType)

SkillLevel = _reflection.GeneratedProtocolMessageType('SkillLevel', (_message.Message,), {
  'DESCRIPTOR' : _SKILLLEVEL,
  '__module__' : 'skill_pb2'
  # @@protoc_insertion_point(class_scope:grpc.weladee.com.SkillLevel)
  })
_sym_db.RegisterMessage(SkillLevel)

Skill = _reflection.GeneratedProtocolMessageType('Skill', (_message.Message,), {
  'DESCRIPTOR' : _SKILL,
  '__module__' : 'skill_pb2'
  # @@protoc_insertion_point(class_scope:grpc.weladee.com.Skill)
  })
_sym_db.RegisterMessage(Skill)

EmployeeSkill = _reflection.GeneratedProtocolMessageType('EmployeeSkill', (_message.Message,), {
  'DESCRIPTOR' : _EMPLOYEESKILL,
  '__module__' : 'skill_pb2'
  # @@protoc_insertion_point(class_scope:grpc.weladee.com.EmployeeSkill)
  })
_sym_db.RegisterMessage(EmployeeSkill)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\033com.frontware.weladee_skillB\013WeladeeGRPCH\003P\001'
  _SKILLTYPE._serialized_start=34
  _SKILLTYPE._serialized_end=360
  _SKILLLEVEL._serialized_start=363
  _SKILLLEVEL._serialized_end=527
  _SKILL._serialized_start=530
  _SKILL._serialized_end=690
  _EMPLOYEESKILL._serialized_start=693
  _EMPLOYEESKILL._serialized_end=900
# @@protoc_insertion_point(module_scope)
